worker_processes 1;
events { worker_connections 64; }

http {
    access_log /dev/stdout;
    error_log /dev/stderr;

    server {
        listen 80;

        location ~ ^/public(/.*)$ {
            fastcgi_pass unix:/var/run/fcgiwrap.sock;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/lib/git-core/git-http-backend;
            fastcgi_param GIT_HTTP_EXPORT_ALL "";
            fastcgi_param GIT_PROJECT_ROOT /srv/git/public;
            fastcgi_param PATH_INFO $1;
        }

        location ~ ^/private(/.*)$ {
            auth_basic "Plimsoll fixture";
            auth_basic_user_file /etc/nginx/htpasswd;

            fastcgi_pass unix:/var/run/fcgiwrap.sock;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /usr/lib/git-core/git-http-backend;
            fastcgi_param GIT_HTTP_EXPORT_ALL "";
            fastcgi_param GIT_PROJECT_ROOT /srv/git/private;
            fastcgi_param PATH_INFO $1;
            fastcgi_param REMOTE_USER $remote_user;
        }
    }
}
